# Generated by Django 3.2 on 2021-04-07 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_department', models.TextField(max_length=200)),
                ('Date_and_Time_of_incident', models.DateTimeField()),
                ('Suspected_Cause', models.TextField(max_length=200)),
                ('environment_incident', models.BooleanField()),
                ('Vehicle', models.BooleanField()),
                ('property_damage', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
